/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MusicPlayer;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Iterator;
import java.util.*;

public class App 
{
    private static ArrayList<Album> albums = new ArrayList<>();

    public static void main(String[] args) 
    {
        //RUN 
        
        Album album = new Album("Album1", "AC/DC",new ArrayList<>());//2 inititalised
        
        album.addSong("TNT",4.5);
        album.addSong("Highway To Hell",3.5);
        album.addSong("ThunderStruck",5.0);
        albums.add(album);
        
        album = new Album("Album2", "Eminem",new ArrayList<>()); ///3rd parameter is an empty array for songs
        
        album.addSong("Rap Gdd",4.5);
        album.addSong("Not Afraid",3.5);
        album.addSong("Lose yourself",4.5);
        
        albums.add(album);
        
        LinkedList<Song> playlist_1=new LinkedList<>();
                albums.get(0).addToPlaylist("TNT", playlist_1);
                albums.get(0).addToPlaylist("Highway To Hell",playlist_1);
                albums.get(1).addToPlaylist("Not Afraid", playlist_1);
                albums.get(1).addToPlaylist("Lose yourself", playlist_1);
                play(playlist_1);
    }
    
    private static void play(LinkedList<Song> playlist)
    {
        Scanner in= new Scanner(System.in);
        boolean quit= false;
        boolean forward=true;
        ListIterator<Song> listIterator =playlist.listIterator();
        
        if(playlist.size()==0)
            System.out.println("This list has no song");
        else{
            System.out.println("Noew playing" + listIterator.next().toString());
            printMenu();
        }
        
        while(!quit)
        {
            int action=in.nextInt();
            in.nextLine();
            switch(action)
            {
                case 0:
                    System.out.println("Playlist Complete");
                    quit=true;
                    break;
                    
                case 1:
                    if(!forward){
                        if(listIterator.hasNext())
                        {
                            listIterator.next();
                        }
                        forward = true;
                    }
                    if(listIterator.hasNext()){
                        System.out.println("Now playing"+ listIterator.next().toString());
                        
                    }
                    else
                    {
                        System.out.println("No Song");
                        forward = false;
                    }
                    break;
                case 2:
                    if(forward)
                    {
                        if(listIterator.hasPrevious())
                            System.out.println("Now Playing"+ listIterator.previous().toString());
                    }
                    else
                    {
                        System.out.println("First Song");
                        forward = false;
                    }
                    break;
                case 3:
                    if(listIterator.hasPrevious())
                    {
                        System.out.println("Now Playing"+listIterator.previous().toString());
                        forward =false;
                    }
                    else
                    {
                        if(listIterator.hasNext())
                        {
                            System.out.println("now playing"+listIterator.next().toString());
                            forward = true;
                        }
                        else
                        {
                            System.out.println("we have reached to the end of list");
                        }
                    }
                    break;
                case 4:
                
                    printList(playlist);
                    break;
                case 5:
                    printMenu();
                    break;
                case 6:
                    if (playlist.size()>0)
                    {
                        if(listIterator.hasNext())
                        {
                            System.out.println("Now Playing"+listIterator.next().toString());
                        
                        }
                        else
                        {
                            if(listIterator.hasPrevious())
                                System.out.println("Now Playing "+listIterator.previous().toString());
                        }
                    }
            }
        }
    }
        private static void printMenu()
        {
            System.out.println("Options \n press");
            System.out.println("0 - to  quit\n"+
                                "1 - to  play neext song"+
                                "2 - to  play previous song\n"+
                                "3 - to  to replay the song\n"+
                                "4 - to  list of all songs\n"+
                                "5 - to  print all available options\n"+
                                "6 - to  delete current song");
            
        }
        
        private static void printList(LinkedList<Song> playlist)
        {
            Iterator<Song> iterator = playlist.iterator();
            System.out.println("______________");
        
            while (iterator.hasNext())
            {
                System.out.println(iterator.next());
            }
            System.out.println("______________");
        }        
    }
//Do you hear anything?
//why would i hear anything?

